language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
rvm:
  - 2.4.6
  - 2.5.5
before_install:
  - gem update --system
  - gem install -v 1.11.2 bundler --no-rdoc --no-ri
install:
  - bundle install --path vendor/bundle
  - cd test/sample && yarn install && cd -
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
script:
  - bundle exec rake
